[tool.poetry]
name = "task4"
version = "0.1.0"
description = ""
authors = ["Alfarabi09 <fara2001@mail.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
django = "^4.2.6"
gunicorn = "^21.2.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
